# Generated by Django 4.2.1 on 2023-07-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_time_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
