# Generated by Django 4.2.1 on 2023-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='start_date',
            field=models.DateField(auto_created=True),
        ),
    ]
