# Generated by Django 4.2.1 on 2023-06-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalregister', '0004_alter_doctorpatient_admission_date_and_more'),
        ('reminder', '0002_alter_prescription_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(choices=[('1 X 1', '1 X 1'), ('1 X 2', '1 X 2'), ('1 X 3', '1 X 3'), ('2 X 1', '2 X 1'), ('2 X 2', '2 X 2'), ('2 X 3', '2 X 3'), ('3 X 1', '3 X 1'), ('3 X 2', '3 X 2'), ('3 X 3', '3 X 3')], default='1 X 3', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalregister.doctorpatient'),
        ),
    ]
