# Generated by Django 4.2.1 on 2023-05-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalregister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
