# Generated by Django 4.2.1 on 2023-06-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalregister', '0002_patientdischargedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctor',
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(auto_created=True)),
                ('end_admission', models.DateField(default=None)),
                ('assignedDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalregister.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalregister.patient')),
            ],
        ),
    ]
