# Generated by Django 4.2.1 on 2023-06-22 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalregister', '0003_remove_patient_assigneddoctor_doctorpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatient',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doctorpatient',
            name='end_admission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
