# Generated by Django 4.2.1 on 2023-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalregister', '0004_alter_doctorpatient_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatient',
            name='end_admission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
